[User]created user app
wecode-bootcamp-korea/13-aircnb-backend pull request #12
Opened 2020-11-11 07:31 UTC by adriankim18

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-11 08:10 UTC, ulfrid requested changes

2020-11-11 08:10 UTC, devops-andrew commented on user/views.py
> +            print(kakao_identity)
print.제거해주세요~

2020-11-11 08:10 UTC, devops-andrew commented on user/views.py
> +            try:
try는 상단의 한번의 선언이면 충분합니다.

2020-11-11 08:10 UTC, devops-andrew commented on user/views.py
> +        except KeyError:
이부분은 익셉션 처리가 아니라 위쪽의 headers.get('AUTHORIZATION')을 if 로 확인해서 받아졌으면 통과 not이면 아래 메세지가 나가게 처리해야 할것 같습니다.

2020-11-11 08:10 UTC, devops-andrew commented on user/views.py
> +            except KeyError:
인덴트 조정해주세요.

2020-11-11 08:10 UTC, ulfrid commented on user/views.py
> +
빈줄 제거해주세요.

2020-11-11 08:10 UTC, ulfrid commented on user/views.py
> +
빈줄 제거해주세요.

2020-11-11 08:10 UTC, ulfrid commented on user/views.py
> +
빈줄 제거해주세요.

2020-11-11 08:10 UTC, ulfrid commented on user/views.py
> +
빈 줄 제거해 주세요.

2020-11-11 08:10 UTC, ulfrid commented on user/views.py
> +
여기도 제거해주세요.

2020-11-11 08:10 UTC, ulfrid commented on user/views.py
> +
여기도 제거해주세요.

2020-11-12 08:43 UTC, ulfrid requested changes
수정사항 반영해 주세요.

2020-11-12 08:43 UTC, ulfrid commented on user/views.py
> +        except Exception as e:
이 익셉션은 모든 익셉션을 가로채게 될것 같은데 이렇게 되면 제대로된 에러 처리가 불가능할것 같습니다. 물론 에러를 뿌려주고 계시지만 이 방법은 권장되지 않습니다. 이렇게 에러가 난다면 핸들한다고 해도 스테이터스코드는 500이 맞습니다. 제거해주세요.

2020-11-12 08:43 UTC, ulfrid commented on user/views.py
> +        except Exception as e:
제거해주세요. 정말 여기서 필요한 익셉션을 잡아주세요. KeyError를 잡아야 할 것 같습니다.

2020-11-12 08:43 UTC, ulfrid commented on user/views.py
> +            print(list(liked_stays))
print 제거해주세요.

2020-11-12 08:43 UTC, ulfrid commented on user/views.py
> +        except Exception as e:
제거해주세요

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'MESSAGE':f'ERROR {e}'}, status = 400)
```suggestion
                    return JsonResponse({'MESSAGE' : 'SUCCESS' , 'AUTHORIZATION' : jwt.encode({'id' : account.id}, SECRET_KEY, ALGORITHM).decode()}, status = 200)
                return JsonResponse({'MESSAGE' : 'EMAIL_PASSWORD_INVALID'}, status = 400)
            return JsonResponse({'MESSAGE' : 'EMAIL_DOES_NOT_EXIST'}, status = 400)
        except Exception as e:
            return JsonResponse({'MESSAGE':f'ERROR {e}'}, status = 400)
```

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'MESSAGE':f'ERROR {e}'}, status = 400)
else가 없어도 바로 위의 if문이 만족되지 않는다면 바로 도달할 수 있는 로직입니다. 꼭 필요한 경우가 아니면 else를 사용하지 않는 것이 보다 파이썬다운 코딩 스타일입니다. else는  지워주셔도 됩니다 :)

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +            if google_identity['email_verified'] == 'true' :
```suggestion
            if google_identity['email_verified']:
```
파이썬에서는 if 조건문 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +            if google_identity['email_verified'] == 'false' :
```suggestion
            if not google_identity['email_verified']:
```
파이썬에서는 if 조건문 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({'MESSAGE' : 'NON_EXISTANT_STAY'}, status = 400)
created가 True일 때 False일 때가 둘 중 하나에는 무조건 해당되기 때문에
그보다 아래에 있는 코드는 도달할 수가 없습니다. 유효한 stay인지 판단하는 부분은 created를 평가하는 곳보다 위에 있어야 겠네요 :)

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +                return  JsonResponse({'SUCCESS' : 'LIKED'}, status = 200)
```suggestion
            if created :
                return  JsonResponse({'SUCCESS' : 'LIKED'}, status = 200)
            return JsonResponse({'SUCCESS' : 'UNLIKED'}, status = 202)
```

2020-11-12 14:52 UTC, soheon-lee commented on user/views.py
> +                #                     stay.review_set.aggregate(Avg('value_star'))['value_star__avg'])/6
사용하지 않는 코드는 다른 곳에 백업해두시고, 주석처리한 내용은 제거해주세요

2020-11-12 15:24 UTC, lordmyshepherd commented
LGTM 👍

2020-11-12 15:25 UTC, merged